# Generated by Django 4.1.7 on 2023-03-28 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner_heading', models.CharField(max_length=200)),
                ('banner_image', models.ImageField(upload_to='banner_images')),
            ],
        ),
        migrations.CreateModel(
            name='Collaboration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collab_heading', models.CharField(max_length=100)),
                ('collab_image', models.ImageField(upload_to='collab_images')),
                ('collab_data', models.CharField(max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_heading', models.CharField(max_length=50)),
                ('product_data', models.CharField(max_length=400)),
                ('product_image', models.ImageField(upload_to='product_images')),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=50)),
                ('star_rating', models.CharField(max_length=50)),
                ('feedback', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Unique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_heading', models.CharField(max_length=100)),
                ('unique_image', models.ImageField(upload_to='unique_images')),
            ],
        ),
        migrations.CreateModel(
            name='Variants',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variant_heading', models.CharField(max_length=50)),
                ('variant_image', models.ImageField(upload_to='variants_images')),
                ('variant_data', models.CharField(max_length=400)),
            ],
        ),
    ]
