# Generated by Django 4.1.7 on 2023-03-28 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sitedata', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='banner_image',
            field=models.ImageField(blank=True, null=True, upload_to='banner_images'),
        ),
    ]
