# Generated by Django 4.1.7 on 2023-03-28 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sitedata', '0005_alter_collaboration_collab_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collaboration',
            name='collab_image',
            field=models.ImageField(blank=True, null=True, upload_to='media/collab_images'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_image',
            field=models.ImageField(blank=True, null=True, upload_to='media/product_images'),
        ),
        migrations.AlterField(
            model_name='unique',
            name='unique_image',
            field=models.ImageField(blank=True, null=True, upload_to='media/unique_images'),
        ),
        migrations.AlterField(
            model_name='variants',
            name='variant_image',
            field=models.ImageField(blank=True, null=True, upload_to='media/variants_images'),
        ),
    ]
