# Generated by Django 4.1.7 on 2023-03-29 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sitedata', '0006_alter_collaboration_collab_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Homesection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner_heading', models.CharField(max_length=200)),
                ('banner_image', models.ImageField(blank=True, null=True, upload_to='media/banner_images')),
                ('best_seller_heading', models.CharField(max_length=50)),
                ('best_seller_image', models.ImageField(blank=True, null=True, upload_to='media/variants_images')),
                ('best_seller_data', models.CharField(max_length=400)),
                ('unique_heading', models.CharField(max_length=100)),
                ('unique_image', models.ImageField(blank=True, null=True, upload_to='media/unique_images')),
                ('product_heading', models.CharField(max_length=50)),
                ('product_data', models.CharField(max_length=400)),
                ('product_image', models.ImageField(blank=True, null=True, upload_to='media/product_images')),
                ('client_name', models.CharField(max_length=50)),
                ('star_rating', models.CharField(max_length=50)),
                ('feedback', models.CharField(max_length=500)),
                ('collab_heading', models.CharField(max_length=100)),
                ('collab_image', models.ImageField(blank=True, null=True, upload_to='media/collab_images')),
                ('collab_data', models.CharField(max_length=400)),
            ],
        ),
        migrations.DeleteModel(
            name='Banner',
        ),
        migrations.DeleteModel(
            name='Collaboration',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.DeleteModel(
            name='Rating',
        ),
        migrations.DeleteModel(
            name='Unique',
        ),
        migrations.DeleteModel(
            name='Variants',
        ),
    ]
