# Generated by Django 4.1.7 on 2023-03-29 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Sitedata', '0007_homesection_delete_banner_delete_collaboration_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='homesection',
            old_name='feedback',
            new_name='feedback_data',
        ),
        migrations.RemoveField(
            model_name='homesection',
            name='star_rating',
        ),
    ]
