# Generated by Django 4.1.7 on 2023-03-29 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sitedata', '0008_rename_feedback_homesection_feedback_data_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homesection',
            name='banner_heading',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='homesection',
            name='best_seller_data',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='homesection',
            name='best_seller_heading',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='homesection',
            name='best_seller_image',
            field=models.ImageField(blank=True, null=True, upload_to='media/seller_images'),
        ),
        migrations.AlterField(
            model_name='homesection',
            name='client_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='homesection',
            name='collab_data',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='homesection',
            name='collab_heading',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='homesection',
            name='feedback_data',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='homesection',
            name='product_data',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='homesection',
            name='product_heading',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='homesection',
            name='unique_heading',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
