# Generated by Django 4.1.7 on 2023-04-04 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sitedata', '0014_alter_homesection_banner_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homesection',
            name='banner_image',
            field=models.FileField(blank=True, null=True, upload_to='images/'),
        ),
    ]
