# Generated by Django 4.1.7 on 2023-04-04 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sitedata', '0015_alter_homesection_banner_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homesection',
            name='best_seller_image',
            field=models.FileField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='homesection',
            name='collab_image',
            field=models.FileField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='homesection',
            name='product_image',
            field=models.FileField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='homesection',
            name='unique_image',
            field=models.FileField(blank=True, null=True, upload_to='images/'),
        ),
    ]
