# Generated by Django 4.1.7 on 2023-04-05 12:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Sitedata', '0017_remove_homesection_unique_heading_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addunique',
            name='homesection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='adduniques', to='Sitedata.homesection'),
        ),
    ]
