# Generated by Django 4.2 on 2023-04-11 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sitedata', '0025_alter_homesection_product_heading'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homesection',
            name='product_heading',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
