# Generated by Django 4.2 on 2023-04-11 13:52

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Sitedata', '0026_alter_homesection_product_heading'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homesection',
            name='banner_heading',
            field=ckeditor.fields.RichTextField(blank=True, max_length=200, null=True),
        ),
    ]
