# Generated by Django 4.2 on 2023-04-12 05:06

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Sitedata', '0028_alter_homesection_best_seller_data_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addunique',
            name='unique_heading',
            field=ckeditor.fields.RichTextField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='homesection',
            name='best_seller_data',
            field=ckeditor.fields.RichTextField(blank=True, max_length=700, null=True),
        ),
        migrations.AlterField(
            model_name='homesection',
            name='collab_data',
            field=ckeditor.fields.RichTextField(blank=True, max_length=700, null=True),
        ),
        migrations.AlterField(
            model_name='homesection',
            name='feedback_data',
            field=ckeditor.fields.RichTextField(blank=True, max_length=700, null=True),
        ),
        migrations.AlterField(
            model_name='homesection',
            name='product_data',
            field=ckeditor.fields.RichTextField(blank=True, max_length=700, null=True),
        ),
    ]
