# Generated by Django 4.2 on 2023-05-05 11:11

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Sitedata', '0029_alter_addunique_unique_heading_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homesection',
            name='best_seller_data',
        ),
        migrations.RemoveField(
            model_name='homesection',
            name='best_seller_heading',
        ),
        migrations.RemoveField(
            model_name='homesection',
            name='best_seller_image',
        ),
        migrations.AlterField(
            model_name='addunique',
            name='homesection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='home_unique_key', to='Sitedata.homesection'),
        ),
        migrations.CreateModel(
            name='Bestseller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('best_seller_heading', ckeditor.fields.RichTextField(blank=True, max_length=200, null=True)),
                ('best_seller_image', models.FileField(blank=True, null=True, upload_to='images/')),
                ('best_seller_data', ckeditor.fields.RichTextField(blank=True, max_length=700, null=True)),
                ('homesection', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='home_bestseller_key', to='Sitedata.homesection')),
            ],
        ),
    ]
